<a href="https://colab.research.google.com/github/bsong75/brendensong.github.io/blob/main/anomaly_4simple%20python%20methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
import plotly.express as px
warnings.filterwarnings('ignore')
df =  pd.read_csv("/content/sample_data/traffic.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Date      32 non-null     object
 1   Sessions  32 non-null     int64 
dtypes: int64(1), object(1)
memory usage: 640.0+ bytes


In [3]:
df['Date'] = pd.to_datetime(df['Date'])

In [6]:
px.line(data_frame=df, x='Date',y='Sessions',title="Lets view outlier")

In [7]:
px.box(data_frame=df,x='Sessions')

In [8]:
px.violin(data_frame=df,x='Sessions')

In [9]:
# Using IQR to estimate outliers

def traditional_outlier(df,x):
    q1  =  df[x].quantile(.25)
    q3  =  df[x].quantile(.75)
    iqr = q3-q1
    df['Traditional']  = np.where(df[[x]]<(q1-1.5*iqr),-1,
                         np.where(df[[x]]>(q3+1.5*iqr),-1,1))
    return df
traditional_outlier(df, 'Sessions')

Date  Sessions  Traditional
0  2022-05-15       663            1
1  2022-05-16      1627            1
2  2022-05-17      1630            1
3  2022-05-18      1666            1
4  2022-05-19      1604            1
5  2022-05-20      1188            1
6  2022-05-21       435            1
7  2022-05-22       726            1
8  2022-05-23      1565            1
9  2022-05-24      1649            1
10 2022-05-25      4822           -1
11 2022-05-26      1496            1
12 2022-05-27      1235            1
13 2022-05-28       532            1
14 2022-05-29       769            1
15 2022-05-30      6402           -1
16 2022-05-31      1661            1
17 2022-06-01      1568            1
18 2022-06-02      2492            1
19 2022-06-03      1131            1
20 2022-06-04       412            1
21 2022-06-05       678            1
22 2022-06-06      1441            1
23 2022-06-07      1575            1
24 2022-06-08      1595            1
25 2022-06-09      1541            1
26 2022-06-10      1067            1
27 2022-06-11       460            1
28 2022-06-12       702            1
29 2022-06-13      1523            1
30 2022-06-14      1579            1
31 2022-06-15      1548            1

In [10]:
#Isolation Forest
from sklearn.ensemble import IsolationForest

In [11]:
IsolationForest().fit(df[['Sessions']]).predict(df[['Sessions']])

array([ 1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1,  1,  1, -1,  1, -1,  1,
        1, -1,  1, -1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1])

In [12]:
df['Isolation Forest'] = IsolationForest().fit(df[['Sessions']]).predict(df[['Sessions']])

In [13]:
from sklearn.covariance import EllipticEnvelope
EllipticEnvelope().fit(df[['Sessions']]).predict(df[['Sessions']])

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1,
        1, -1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [14]:
from sklearn.neighbors import LocalOutlierFactor
LocalOutlierFactor(n_neighbors=5, novelty=True).fit(df[['Sessions']]).predict(df[['Sessions']])

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1, -1,  1,
        1, -1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [15]:
def outliers_find(df,x):
    df['Local Outlier'] = LocalOutlierFactor(n_neighbors=5, novelty=True).fit(df[[x]]).predict(df[[x]])
    df['Isolation Forest'] = IsolationForest().fit(df[[x]]).predict(df[[x]])
    df['Elliptical'] = EllipticEnvelope().fit(df[[x]]).predict(df[[x]])
    return df

In [17]:
outliers_find(df, 'Sessions')

Date  Sessions  Traditional  Isolation Forest  Local Outlier  \
0  2022-05-15       663            1                 1              1   
1  2022-05-16      1627            1                 1              1   
2  2022-05-17      1630            1                 1              1   
3  2022-05-18      1666            1                 1              1   
4  2022-05-19      1604            1                 1              1   
5  2022-05-20      1188            1                 1              1   
6  2022-05-21       435            1                -1              1   
7  2022-05-22       726            1                 1              1   
8  2022-05-23      1565            1                 1              1   
9  2022-05-24      1649            1                 1              1   
10 2022-05-25      4822           -1                -1             -1   
11 2022-05-26      1496            1                 1             -1   
12 2022-05-27      1235            1                 1              1   
13 2022-05-28       532            1                -1              1   
14 2022-05-29       769            1                 1              1   
15 2022-05-30      6402           -1                -1             -1   
16 2022-05-31      1661            1                 1              1   
17 2022-06-01      1568            1                 1              1   
18 2022-06-02      2492            1                -1             -1   
19 2022-06-03      1131            1                 1              1   
20 2022-06-04       412            1                -1              1   
21 2022-06-05       678            1                 1              1   
22 2022-06-06      1441            1                 1             -1   
23 2022-06-07      1575            1                 1              1   
24 2022-06-08      1595            1                 1              1   
25 2022-06-09      1541            1                 1              1   
26 2022-06-10      1067            1                 1              1   
27 2022-06-11       460            1                -1              1   
28 2022-06-12       702            1                 1              1   
29 2022-06-13      1523            1                 1              1   
30 2022-06-14      1579            1                 1              1   
31 2022-06-15      1548            1                 1              1   

    Elliptical  
0            1  
1            1  
2            1  
3            1  
4            1  
5            1  
6            1  
7            1  
8            1  
9            1  
10          -1  
11           1  
12           1  
13           1  
14           1  
15          -1  
16           1  
17           1  
18          -1  
19           1  
20          -1  
21           1  
22           1  
23           1  
24           1  
25           1  
26           1  
27           1  
28           1  
29           1  
30           1  
31           1

In [ ]:
def outliers_find(df,x):
    q1  =  df[x].quantile(.25)
    q3  =  df[x].quantile(.75)
    iqr = q3-q1
    df['Traditional']  = np.where(df[[x]]<(q1-1.5*iqr),-1,
                         np.where(df[[x]]>(q3+1.5*iqr),-1,1))
    df['Local Outlier'] = LocalOutlierFactor(n_neighbors=5, novelty=True).fit(df[[x]]).predict(df[[x]])
    df['Isolation Forest'] = IsolationForest().fit(df[[x]]).predict(df[[x]])
    df['Eliptic Envelope'] =EllipticEnvelope().fit(df[['Sessions']]).predict(df[['Sessions']])
    return df